### GET
GET http://localhost:3000/api/v1/users




### POST
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":"Chutidet",
    "email":"Chutidet@example.com"
}



### Deleted request to delete a user
DELETE http://localhost:3000/api/v1/users/4


